services:
  minimal-api:
    build:
      context: .
    volumes:
      - ./BlogSystem/Content:/app/Content
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"

    restart: always
